apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: 23934-censor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ilushka8obnimashka/censor.backend:latest
          ports:
            - containerPort: 8000
          env:
            - name: MINIO_ENDPOINT
              value: "minio:9000"
            - name: MINIO_ACCESS_KEY
              value: "minio"
            - name: MINIO_SECRET_KEY
              value: "minio123"
            - name: MINIO_SECURE
              value: "False"
            - name: GIGA_CHAT_KEY
              value: "MDZlMGU2NzItZTBiMC00YTBjLThmN2ItZGE5ZWM4MTE4MGFiOjFkYjA1MDVkLTVmMTgtNDZkOS1iMzI2LTJiOGFlN2U3MWViMQ=="
          resources:
            limits:
              nvidia.com/gpu: 1
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Exists"
          effect: "NoSchedule"

