apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: 23934-censor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      nodeName: spartacus
      containers:
        - name: backend
          image: ilushka8obnimashka/censor.backend:latest
          ports:
            - containerPort: 8000
          env:
            - name: MINIO_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: censor-secrets
                  key: MINIO_ENDPOINT
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: censor-secrets
                  key: MINIO_ACCESS_KEY
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: censor-secrets
                  key: MINIO_SECRET_KEY
            - name: MINIO_SECURE
              valueFrom:
                secretKeyRef:
                  name: censor-secrets
                  key: MINIO_SECURE
            - name: GIGA_CHAT_KEY
              valueFrom:
                secretKeyRef:
                  name: censor-secrets
                  key: GIGA_CHAT_KEY
          resources:
            limits:
              nvidia.com/gpu: 1
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Exists"
          effect: "NoSchedule"

