name: Build and Push Docker Image

on:
  workflow_call:
    outputs:
      backend_service:
        description: "Whether backend service was modified"
        value: ${{ jobs.check.outputs.backend_service }}
      frontend_service:
        description: "Whether frontend service was modified"
        value: ${{ jobs.check.outputs.frontend_service }}

jobs:
  check:
    name: Check changed files
    outputs:
      backend_service: ${{ steps.check_files.outputs.backend_service}}
      frontend_service: ${{ steps.check_files.outputs.frontend_service}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          lfs: true

      - name: check modified files
        id: check_files
        run: |
          echo "=============== list modified files ==============="
          git diff --name-only HEAD^ HEAD

          echo "========== check paths of modified files =========="
          git diff --name-only HEAD^ HEAD > files.txt
          while IFS= read -r file; do
            echo $file
            if [[ $file == backend/* ]]; then
              echo "::set-output name=backend_service::true"
            elif [[ $file == frontend/* ]]; then
              echo "::set-output name=frontend_service::true"
            else
              echo "file does not belong to any service"
            fi
          done < files.txt

  backend_service:
    needs: check
    if: needs.check.outputs.backend_service == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Git LFS Pull
        run: git lfs pull
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish to Registry
        uses: docker/build-push-action@v5
        with:
          context: backend/
          push: true
          tags: ilushka8obnimashka/censor.backend:latest

  frontend_service:
    needs: check
    if: needs.check.outputs.frontend_service == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish to Registry
        uses: docker/build-push-action@v5
        with:
          context: frontend/
          push: true
          tags: ilushka8obnimashka/censor.frontend:latest

